### ISSUE TITLE
ruby_dep dependency not compatible with Ruby 3

### ISSUE THREAD

**Issue by gordielachance** [inkstak/musicbrainz#13]
Hi, I get this notice when trying to update to Ruby 3

```
ruby_dep-1.5.0 requires ruby version >= 2.2.5, ~> 2.2, which is incompatible
with the current version, ruby 3.0.2p107
```

Not supported ?
Thanks for your good work !

**Comment by inkstak** [comment]
Hi, `ruby_dep` is not a dependency of `musicbrainz`.

Are you sure it cames from `muscibrainz` ?  
Do you have the full message from `gem install` or `bundle update`  ?
