### ISSUE TITLE
Cannot coerce property "video" from TrueClass

### ISSUE THREAD

**Issue by PoweredByRobots** [inkstak/musicbrainz#2]
This error crops up from time to time when querying [recordings](https://github.com/inkstak/musicbrainz/blob/master/lib/musicbrainz/models/recording.rb).

The full error is:

> MusicBrainz error: Cannot coerce property "video" from TrueClass to #<Proc:0x0xxxxxxxxxxxxxxx@gempath/musicbrainz-e83fd26e2b25/lib/musicbrainz/models/recording.rb:11 (lambda)>: undefined method `to_i' for true:TrueClass

From my experience, this value comes in as either nil or True. When it's True, we get this error.

**Comment by inkstak** [comment]
@PoweredByRobots Thanks for your PR and sorry for the delay !
