### ISSUE TITLE
Where should I define the configuration ?

### ISSUE THREAD

**Issue by gordielachance** [inkstak/musicbrainz#9]
Hi!
First, thanks you for making this !  All other Musicbrainz gems seems outdated since a long time ago.  Yours is more than welcome !

I'm a Ruby newbie so sorry for this question : 
Where should I define the configuration ?

```
MusicBrainz.configure do |c|
  c.app_name    = 'MyApp'
  c.app_version = '0.0.1.alpha'
  c.contact     = 'john.doe@my.app'
end

client = MusicBrainz::Client.new
```

I would like it to be shared by several files within my app, should I put this somewhere in /config ?
Thanks !

**Comment by inkstak** [comment]
`MusicBrainz.configure` defines a global configuration.
You can then initilaze a `Client` wherever you want.

For example, in a Rails application :

```ruby
# config/initializers/musicbrainz.rb

MusicBrainz.configure do |c|
  c.app_name    = 'MyApp'
  c.app_version = '0.0.1.alpha'
  c.contact     = 'john.doe@my.app'
end
```

```ruby
# app/models/artist.rb

class Artist < ApplicationRecord
  def client
    @client ||= MusicBrainz::Client.new
  end 

  def assign_musicbrainz_uuid
    self.musicbrainz_uuid = client.artists(name)[0].id
  end 

  def musicbrainz_data
    client.artist(musicbrainz_uuid)
  end 
end
```

**Comment by gordielachance** [comment]
Thank you so much !
